[package]
name = "gen_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_parser = {path = "../parser"}
gen_traits = {path = "../traits"}
gen_macros = {path = "../macros"}
syn = {version="2.0.52",features=["full","extra-traits","visit-mut","visit"]}
quote = "1.0.35"
proc-macro2 = "1.0.78"
ulid = "1.1.2"
