[package]
name = "makepad-gen-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_converter = { path = "../../converter" }
gen_utils = { path = "../../utils" }
gen_parser ={ path = "../../parser"}
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.52", features = ["full", "extra-traits"] }
makepad-widgets = { path = "/Users/user/Downloads/makepad-rik/widgets"}
#  E:/Rust/learn/makepad/makepad-rik/widgets