[package]
name = "gen_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_converter = { path = "../converter" }
gen_utils = { path = "../utils", default-features = false, features = ["compiler"] }
makepad_gen_plugin = { path = "../generator/makepad" }
# ark_gen_plugin = { path = "../generator/ark" }
walkdir = "2.5.0"
ansi_term = "0.12.1"
env_logger = "0.11.3"
log = "0.4.21"
notify = "6.1.1"
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0.202", features = ["derive"] }
rmp-serde = "1.3.0"
sha2 = "0.10.8"
lazy_static = "1.5.0"
toml_edit = "0.22.19"
